import Link from 'next/link';
import { ArrowRight,Heart,Mail,MapPin,ShieldCheck,Sparkles } from 'lucide-react';

export default function About(){return <main className="min-h-screen bg-[#fbf8f1] pt-18">
 <section className="paper-grid soft-noise px-5 py-24 text-center"><div className="mx-auto max-w-4xl"><p className="mb-5 text-xs font-bold uppercase tracking-[.2em] text-[#255c45]">Our story</p><h1 className="font-display text-5xl leading-[.98] md:text-7xl">Technology should help us <em>remember each other.</em></h1><p className="mx-auto mt-7 max-w-2xl text-lg leading-8 text-[#17211c]/60">Katha began with a simple fear: a lifetime of stories can disappear behind one forgotten password. We are building a gentler kind of technology—one that protects the meaning, not only the files.</p></div></section>
 <section className="px-5 py-20"><div className="mx-auto grid max-w-6xl gap-6 md:grid-cols-3">{[[Heart,'Human first','Every feature begins with a family, a memory, and the wish to stay connected.'],[ShieldCheck,'Private always','Your personal archive deserves careful access, clear ownership, and no surprises.'],[MapPin,'Born in India','Built with the richness of oral history, family traditions, and generations in mind.']].map(([Icon,title,copy])=><article key={String(title)} className="rounded-[2rem] border border-[#17211c]/10 bg-white p-8"><Icon className="mb-8 text-[#e86f51]"/><h2 className="font-display text-2xl">{String(title)}</h2><p className="mt-3 text-sm leading-7 text-[#17211c]/55">{String(copy)}</p></article>)}</div></section>
 <section className="px-5 pb-20"><div className="mx-auto grid max-w-6xl overflow-hidden rounded-[2.5rem] bg-[#17211c] text-white md:grid-cols-2"><div className="p-9 md:p-14"><Sparkles className="mb-8 text-[#e86f51]"/><p className="font-display text-3xl leading-snug md:text-4xl">“We do not just store files. We create a place where a person can still be felt.”</p><div className="mt-8 border-t border-white/10 pt-6"><p className="font-bold">Team Katha</p><p className="mt-1 text-sm text-white/45">Builders, listeners, and memory keepers</p></div></div><div className="flex flex-col justify-center bg-[#dfe7da] p-9 text-[#17211c] md:p-14"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#255c45]">Come build this with us</p><h2 className="mt-4 font-display text-4xl">Every family remembers differently.</h2><p className="mt-4 text-sm leading-7 text-[#17211c]/60">Tell us what preserving a life should feel like for yours.</p><a href="mailto:kathasystems@gmail.com" className="mt-7 inline-flex w-fit items-center gap-3 rounded-full bg-[#255c45] px-6 py-3.5 text-sm font-bold text-white"><Mail size={17}/>Write to Katha</a></div></div></section>
 <section className="px-5 pb-24 text-center"><h2 className="font-display text-4xl">Begin with one story.</h2><Link href="/register" className="mt-6 inline-flex items-center gap-2 rounded-full bg-[#e86f51] px-7 py-4 text-sm font-bold text-white">Create your archive <ArrowRight size={17}/></Link></section>
 </main>}
