'use client';
import { useState } from 'react';
import Link from 'next/link';
import { ArrowLeft,ArrowRight,KeyRound,Loader2,Lock,Mail,Quote } from 'lucide-react';
import { getSecurityQuestion,loginUser,verifySecurityAnswer } from '../actions';
export default function Login(){const [mode,setMode]=useState<'login'|'recover'>('login'),[question,setQuestion]=useState(''),[email,setEmail]=useState(''),[error,setError]=useState(''),[loading,setLoading]=useState(false);
 const enter=async(fd:FormData)=>{setLoading(true);setError('');const r=await loginUser(fd);if(r.success)window.location.href=`/?email=${encodeURIComponent(r.user.email)}&name=${encodeURIComponent(r.user.name)}`;else setError(r.error||'We could not open that vault.');setLoading(false)};
 const identify=async(fd:FormData)=>{setLoading(true);setError('');const value=String(fd.get('email'));setEmail(value);const r=await getSecurityQuestion(value);if(r.success)setQuestion(r.question);else setError(r.error||'No vault was found.');setLoading(false)};
 const answer=async(fd:FormData)=>{setLoading(true);setError('');const r=await verifySecurityAnswer(email,String(fd.get('answer')));if(r.success&&r.user)window.location.href=`/?email=${encodeURIComponent(r.user.email)}&name=${encodeURIComponent(r.user.name)}`;else setError(r.error||'That answer did not match.');setLoading(false)};
 return <main className="grid min-h-screen bg-[#fbf8f1] pt-18 lg:grid-cols-2"><section className="soft-noise hidden items-end bg-[#dfe7da] p-14 lg:flex"><div className="max-w-lg"><Quote className="mb-6 text-[#e86f51]"/><p className="font-display text-5xl leading-tight">“Somewhere in your stories, someone will find their way home.”</p><p className="mt-6 text-sm text-[#17211c]/50">Your private Katha archive</p></div></section><section className="flex items-center justify-center px-5 py-16"><div className="w-full max-w-md">{mode==='login'?<><p className="text-xs font-bold uppercase tracking-[.2em] text-[#255c45]">Welcome back</p><h1 className="mt-4 font-display text-5xl">Enter your vault.</h1><p className="mt-3 text-sm text-[#17211c]/55">Your memories are waiting where you left them.</p><Form action={enter} loading={loading} error={error} button="Open my vault"><Field icon={Mail} name="email" type="email" placeholder="Email address"/><Field icon={Lock} name="password" type="password" placeholder="Password"/></Form><button onClick={()=>{setMode('recover');setError('')}} className="mt-5 text-sm font-bold text-[#255c45]">I need help getting in</button></>:<><button onClick={()=>{setMode('login');setQuestion('');setError('')}} className="mb-7 flex items-center gap-2 text-sm font-bold text-[#17211c]/50"><ArrowLeft size={16}/>Back to login</button><p className="text-xs font-bold uppercase tracking-[.2em] text-[#255c45]">Vault recovery</p><h1 className="mt-4 font-display text-5xl">Let’s find your story.</h1>{question?<><div className="mt-6 rounded-2xl bg-[#dfe7da] p-5 font-display text-xl">{question}</div><Form action={answer} loading={loading} error={error} button="Verify and enter"><Field icon={KeyRound} name="answer" placeholder="Your secret answer"/></Form></>:<><p className="mt-3 text-sm text-[#17211c]/55">Enter the email connected to your archive.</p><Form action={identify} loading={loading} error={error} button="Find my vault"><Field icon={Mail} name="email" type="email" placeholder="Email address"/></Form></>}</>}<p className="mt-10 border-t border-[#17211c]/10 pt-6 text-sm text-[#17211c]/50">New to Katha? <Link href="/register" className="font-bold text-[#255c45]">Create your archive</Link></p></div></section></main>}
function Field({icon:Icon,...props}:{icon:typeof Mail;name:string;type?:string;placeholder:string}){return <label className="relative block"><Icon className="absolute left-4 top-4 text-[#255c45]" size={18}/><input required className="w-full rounded-2xl border border-[#17211c]/15 bg-white py-4 pl-12 pr-4 text-sm focus:border-[#255c45]" {...props}/></label>}
function Form({action,loading,error,button,children}:{action:(fd:FormData)=>void;loading:boolean;error:string;button:string;children:React.ReactNode}){return <form action={action} className="mt-8 space-y-4">{children}{error&&<p className="rounded-xl bg-red-50 px-4 py-3 text-sm text-red-700">{error}</p>}<button disabled={loading} className="flex w-full items-center justify-center gap-2 rounded-full bg-[#17211c] py-4 text-sm font-bold text-white hover:bg-[#255c45]">{loading?<Loader2 className="animate-spin" size={17}/>:<>{button}<ArrowRight size={17}/></>}</button></form>}
