'use client';
import { useEffect,useState } from 'react';
import { Check,Loader2,Lock,ShieldCheck,Sparkles,X } from 'lucide-react';
import { checkPremiumStatus,loginUser,upgradeToPremium } from '../actions';
type PayUser={name:string;email:string};
declare global{interface Window{Razorpay:new(options:Record<string,unknown>)=>{open:()=>void}}}
const free=['2 conversations with your archive','Secure memory uploads','Your personal story profile'];
const plusFeatures=['Unlimited archive conversations','Unlimited memory uploads','Scheduled legacy delivery','Priority nominee handover'];
export default function Pricing(){
 const [premium,setPremium]=useState(false),[loading,setLoading]=useState(true),[processing,setProcessing]=useState(false),[verify,setVerify]=useState(false),[email,setEmail]=useState(''),[pass,setPass]=useState(''),[message,setMessage]=useState('');
 useEffect(()=>{void(async()=>{try{const raw=localStorage.getItem('katha_session');if(raw){const u=JSON.parse(raw);const r=await checkPremiumStatus(u.email);if(r.success)setPremium(r.isPremium??false);}}finally{setLoading(false);}})()},[]);
 const notice=(text:string)=>{setMessage(text);setTimeout(()=>setMessage(''),4000)};
 const begin=()=>{if(!localStorage.getItem('katha_session')){notice('Please enter your vault before upgrading.');return}setVerify(true)};
 const pay=(user:PayUser)=>{if(!window.Razorpay){notice('Payment service is unavailable. Please try again.');return}new window.Razorpay({key:process.env.NEXT_PUBLIC_RAZORPAY_KEY_ID,amount:2900,currency:'INR',name:'Katha',description:'Katha Plus',prefill:user,theme:{color:'#255c45'},handler:async()=>{setProcessing(true);const r=await upgradeToPremium(user.email);if(r.success){setPremium(true);notice('Welcome to Katha Plus.')}setProcessing(false)}}).open()};
 const authenticate=async(e:React.FormEvent)=>{e.preventDefault();setProcessing(true);const fd=new FormData();fd.append('email',email);fd.append('password',pass);const r=await loginUser(fd);if(r.success){setVerify(false);pay(r.user)}else notice('Those details did not match your vault.');setProcessing(false)};
 if(loading)return <div className="grid min-h-screen place-items-center bg-[#fbf8f1]"><Loader2 className="animate-spin text-[#255c45]"/></div>;
 return <main className="min-h-screen bg-[#fbf8f1] px-5 pb-24 pt-32">
  {message&&<div className="fixed left-1/2 top-24 z-[200] -translate-x-1/2 rounded-full bg-[#17211c] px-6 py-3 text-sm text-white shadow-xl">{message}</div>}
  {verify&&<div className="fixed inset-0 z-[100] grid place-items-center bg-[#17211c]/60 p-5 backdrop-blur-sm"><div className="relative w-full max-w-sm rounded-[2rem] bg-[#fbf8f1] p-8 shadow-2xl"><button onClick={()=>setVerify(false)} className="absolute right-5 top-5"><X size={18}/></button><Lock className="mb-5 text-[#e86f51]"/><h2 className="font-display text-3xl">Confirm it’s you</h2><p className="mt-2 text-sm text-[#17211c]/55">Re-enter your vault details before payment.</p><form onSubmit={authenticate} className="mt-6 space-y-3"><input type="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="Email address" className="w-full rounded-2xl border border-[#17211c]/15 bg-white px-4 py-3.5 text-sm"/><input type="password" required value={pass} onChange={e=>setPass(e.target.value)} placeholder="Password" className="w-full rounded-2xl border border-[#17211c]/15 bg-white px-4 py-3.5 text-sm"/><button disabled={processing} className="w-full rounded-full bg-[#255c45] py-3.5 text-sm font-bold text-white">{processing?'Checking…':'Confirm and pay ₹29'}</button></form></div></div>}
  <header className="mx-auto max-w-3xl text-center"><p className="text-xs font-bold uppercase tracking-[.2em] text-[#255c45]">Simple pricing</p><h1 className="mt-5 font-display text-5xl md:text-7xl">Begin free. Grow when your <em>story does.</em></h1><p className="mx-auto mt-6 max-w-xl leading-7 text-[#17211c]/55">Preserve the first chapters at no cost. Upgrade when you want deeper conversations and family handover tools.</p></header>
  <section className="mx-auto mt-14 grid max-w-5xl gap-5 md:grid-cols-2"><Plan name="Katha Free" price="₹0" note="A thoughtful place to begin" features={free}/><div className="relative overflow-hidden rounded-[2.5rem] bg-[#17211c] p-8 text-white shadow-2xl md:p-10"><span className="absolute right-0 top-0 rounded-bl-2xl bg-[#e86f51] px-5 py-2 text-xs font-bold">MOST LOVED</span><Sparkles className="mb-8 text-[#e86f51]"/><h2 className="font-display text-3xl">Katha Plus</h2><p className="mt-2 text-sm text-white/50">For a growing family archive</p><p className="my-8 font-display text-5xl">₹29 <span className="font-sans text-sm text-white/40">/ month</span></p><ul className="space-y-4">{plusFeatures.map(x=><li key={x} className="flex gap-3 text-sm"><Check size={17} className="shrink-0 text-[#e86f51]"/>{x}</li>)}</ul>{premium?<div className="mt-9 flex items-center justify-center gap-2 rounded-full bg-white/10 py-4 text-sm font-bold"><ShieldCheck size={17}/>Your plan is active</div>:<button onClick={begin} disabled={processing} className="mt-9 w-full rounded-full bg-[#e86f51] py-4 text-sm font-bold transition hover:bg-[#f08063]">{processing?'Preparing…':'Upgrade to Katha Plus'}</button>}</div></section>
  <p className="mx-auto mt-8 max-w-xl text-center text-xs text-[#17211c]/40"><ShieldCheck className="mr-2 inline" size={14}/>Secure payment through Razorpay. Cancel anytime.</p>
 </main>}
function Plan({name,price,note,features}:{name:string;price:string;note:string;features:string[]}){return <div className="rounded-[2.5rem] border border-[#17211c]/10 bg-white p-8 md:p-10"><h2 className="font-display text-3xl">{name}</h2><p className="mt-2 text-sm text-[#17211c]/50">{note}</p><p className="my-8 font-display text-5xl">{price}</p><ul className="space-y-4">{features.map(x=><li key={x} className="flex gap-3 text-sm"><Check size={17} className="shrink-0 text-[#255c45]"/>{x}</li>)}</ul><div className="mt-9 rounded-full border border-[#17211c]/10 py-4 text-center text-sm font-bold text-[#17211c]/45">Included with every account</div></div>}
