'use client';
import { useEffect,useState } from 'react';import { Download,Eye,FileText,HardDrive,Loader2,ShieldCheck,Users,X } from 'lucide-react';import { getAdminStats,getUserDetails } from '../actions';
type User={name:string;email:string};type File={id:number;file_name:string;file_type:string;user_email:string;file_url?:string};type Stats={users:User[];vaultFiles:File[]};type Detail={user:User;files:File[]};
export default function Admin(){const [data,setData]=useState<Stats|null>(null),[selected,setSelected]=useState<Detail|null>(null),[loading,setLoading]=useState(true);
 useEffect(()=>{void getAdminStats().then(r=>{if(r.success)setData({users:(r.users||[]) as User[],vaultFiles:(r.vaultFiles||[]) as File[]});setLoading(false)})},[]);
 const view=async(email:string)=>{const r=await getUserDetails(email);if(r.success)setSelected({user:r.user as User,files:(r.files||[]) as File[]})};
 if(loading)return <div className="grid min-h-screen place-items-center bg-[#f4f0e7]"><Loader2 className="animate-spin text-[#255c45]"/></div>;
 return <main className="min-h-screen bg-[#f4f0e7] px-5 pb-24 pt-28"><div className="mx-auto max-w-6xl"><header className="mb-10 flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-[.2em] text-[#255c45]"><ShieldCheck size={15}/>Private administration</p><h1 className="mt-3 font-display text-5xl">Archive overview</h1><p className="mt-2 text-sm text-[#17211c]/50">A clear view of Katha members and their stored memories.</p></div></header><section className="mb-6 grid gap-4 sm:grid-cols-2"><Stat icon={Users} label="People with archives" value={data?.users.length||0}/><Stat icon={HardDrive} label="Memories preserved" value={data?.vaultFiles.length||0}/></section><section className="overflow-hidden rounded-[2rem] border border-[#17211c]/10 bg-[#fbf8f1]"><div className="border-b border-[#17211c]/10 p-6"><h2 className="font-display text-2xl">Archive members</h2></div><div className="overflow-x-auto"><table className="w-full min-w-[650px] text-left"><thead className="text-xs uppercase tracking-[.12em] text-[#17211c]/40"><tr><th className="p-5">Name</th><th className="p-5">Email</th><th className="p-5">Memories</th><th className="p-5">Details</th></tr></thead><tbody className="divide-y divide-[#17211c]/10">{data?.users.map(u=><tr key={u.email} className="hover:bg-white"><td className="p-5 font-bold">{u.name}</td><td className="p-5 text-sm text-[#17211c]/50">{u.email}</td><td className="p-5 font-display text-xl text-[#255c45]">{data.vaultFiles.filter(f=>f.user_email===u.email).length}</td><td className="p-5"><button onClick={()=>view(u.email)} className="flex items-center gap-2 rounded-full border border-[#17211c]/15 px-4 py-2 text-xs font-bold hover:bg-[#255c45] hover:text-white"><Eye size={14}/>Open archive</button></td></tr>)}</tbody></table></div></section></div>
 {selected&&<div className="fixed inset-0 z-[100] grid place-items-center bg-[#17211c]/65 p-5 backdrop-blur-sm"><div className="max-h-[85vh] w-full max-w-2xl overflow-hidden rounded-[2rem] bg-[#fbf8f1] shadow-2xl"><header className="flex items-start justify-between bg-[#17211c] p-7 text-white"><div><h2 className="font-display text-3xl">{selected.user.name}</h2><p className="mt-1 text-sm text-white/45">{selected.user.email}</p></div><button onClick={()=>setSelected(null)} className="rounded-full border border-white/15 p-2"><X size={18}/></button></header><div className="max-h-[55vh] overflow-y-auto p-6 custom-scrollbar"><p className="mb-4 text-xs font-bold uppercase tracking-[.18em] text-[#255c45]">Preserved memories</p>{selected.files.length?<div className="space-y-2">{selected.files.map(f=><div key={f.id} className="flex items-center justify-between gap-4 rounded-2xl bg-white p-4"><div className="flex min-w-0 gap-3"><FileText className="shrink-0 text-[#e86f51]"/><div className="min-w-0"><p className="truncate text-sm font-bold">{f.file_name}</p><p className="text-xs text-[#17211c]/40">{f.file_type}</p></div></div><div className="flex"><a aria-label="View" href={f.file_url||`/uploads/${f.file_name}`} target="_blank" className="p-2"><Eye size={16}/></a><a aria-label="Download" href={f.file_url||`/uploads/${f.file_name}`} download className="p-2 text-[#255c45]"><Download size={16}/></a></div></div>)}</div>:<p className="rounded-2xl border border-dashed p-10 text-center text-sm text-[#17211c]/45">No memories have been added yet.</p>}</div></div></div>}
 </main>}
function Stat({icon:Icon,label,value}:{icon:typeof Users;label:string;value:number}){return <div className="flex items-center justify-between rounded-[2rem] border border-[#17211c]/10 bg-[#fbf8f1] p-7"><div><p className="text-xs uppercase tracking-[.12em] text-[#17211c]/45">{label}</p><p className="mt-2 font-display text-5xl">{value}</p></div><span className="grid h-14 w-14 place-items-center rounded-full bg-[#dfe7da] text-[#255c45]"><Icon/></span></div>}
